//Пимер ввода данных в массив:
      // id: 1,
      // img: require('./images/books/book1.png'),
      // title: 'Тихие слова любви',
      // author: 'Сара Джио1',
      // cost: '2990',
      // new: true,
      // best: true,
      // genre: 'hud-lit',
      // available: 5,
      // ISBN: '978-5-04-106152-4',
      // janr: 'Современная зарубежная проза',
      // company: 'Эскимо',
      // series: 'Триллер-клуб "Ночь". Психологический триллер',
      // age: '16+',
      // year: 2020,
      // binding: 'Твёрдый',
      // pages: 384,
      // weight: 392,
      // size: '207*133*25',
      // language: 'Русский',
      // popular: true,
      // inCart: false,
      //inFavorites: false,
      // annotation: 'Два брата. Трагическое прошлое, преследующее их до сих пор. Оба приняли неверное решение, стоившее жизни их сестре. Один посвятил себя мести. Другой - прощению. И оба платят за свой выбор - гораздо больше, чем могли себе представить… С того времени, как неизвестный похитил и убил их сестру, прошло 20 лет. Адам, старший брат, выбрал профессию частного детектива, нелюдимого и циничного, оказывающего услуги людям из мира криминала. Младший, Кент, стал футбольным тренером, уважаемым членом общины и глубоко верующим человеком. Они не общаются, продолжая винить друг друга за то, что произошло с их сестрой. До тех пор пока не происходит новая трагедия, уже с другой девушкой, потому что оба брата вновь приняли неверное решение… Этот роман - история семейной трагедии, вины и искупления.'

export let books = [
    {
      id: 1,
      img: require('./images/books/book1.png'),
      title: 'Тихие слова любви',
      author: 'Сара Джио1',
      cost: 2990,
      new: true,
      best: true,
      genre: 'hud-lit',
      available: 5,
      ISBN: '978-5-04-106152-4',
      janr: 'Современная зарубежная проза',
      company: 'Эскимо',
      series: 'Триллер-клуб "Ночь". Психологический триллер',
      age: '16+',
      year: 2020,
      binding: 'Твёрдый',
      pages: 384,
      weight: 392,
      size: '207*133*25',
      language: 'Русский',
      popular: true,
      inCart: false,
      inFavorites: false,
      annotation: 'Два брата. Трагическое прошлое, преследующее их до сих пор. Оба приняли неверное решение, стоившее жизни их сестре. Один посвятил себя мести. Другой - прощению. И оба платят за свой выбор - гораздо больше, чем могли себе представить… С того времени, как неизвестный похитил и убил их сестру, прошло 20 лет. Адам, старший брат, выбрал профессию частного детектива, нелюдимого и циничного, оказывающего услуги людям из мира криминала. Младший, Кент, стал футбольным тренером, уважаемым членом общины и глубоко верующим человеком. Они не общаются, продолжая винить друг друга за то, что произошло с их сестрой. До тех пор пока не происходит новая трагедия, уже с другой девушкой, потому что оба брата вновь приняли неверное решение… Этот роман - история семейной трагедии, вины и искупления.'
    },
    {
      id: 2,
      img: require('./images/books/book1.png'),
      title: 'Тихие слова любви',
      author: 'Сара Джио2',
      cost: 3000,
      new: false,
      best: true,
      genre: 'hud-lit',
      available: 3,
      inCart: false,
      inFavorites: false,
    },
    {
      id: 3,
      img: require('./images/books/book1.png'),
      title: 'Тихие слова любви',
      author: 'Сара Джио3',
      cost: 2990,
      new: true,
      best: false,
      inCart: false,
      inFavorites: false,
      available: 0,
      genre: 'hud-lit'
    },
    {
      id: 4,
      img: require('./images/books/book1.png'),
      title: 'Тихие слова любви',
      author: 'Сара Джио4',
      cost: 2990,
      new: false,
      best: false,
      inCart: false,
      inFavorites: false,
      available: 5,
    },
    {
      id: 5,
      img: require('./images/books/book1.png'),
      title: 'Тихие слова любви',
      author: 'Сара Джио5',
      cost: 2990,
      new: true,
      best: true,
      inCart: false,
      inFavorites: false,
      available: 5,
    },
    {
      id: 6,
      img: require('./images/books/book1.png'),
      title: 'Тихие слова любви',
      author: 'Сара Джио6',
      cost: 2990,
      new: false,
      best: true,
      inCart: false,
      inFavorites: false,
      available: 5,
      genre: 'hud-lit'
    },
    {
      id: 7,
      img: require('./images/books/book1.png'),
      title: 'Тихие слова любви',
      author: 'Сара Джио7',
      cost: 2990,
      new: true,
      best: false,
      inCart: false,
      inFavorites: false,
      available: 5,
      genre: 'hud-lit'
    },
    {
      id: 8,
      img: require('./images/books/book1.png'),
      title: 'Тихие слова любви',
      author: 'Сара Джио8',
      cost: 2990,
      new: true,
      best: true,
      inCart: false,
      inFavorites: false,
      available: 5,
    },
    {
      id: 9,
      img: require('./images/books/book1.png'),
      title: 'Тихие слова любви',
      author: 'Сара Джио9',
      cost: 2990,
      new: true,
      best: true,
      inCart: false,
      inFavorites: false,
      available: 5,
    },
    {
      id: 10,
      img: require('./images/books/book1.png'),
      title: 'Тихие слова любви',
      author: 'Сара Джио10',
      cost: 2990,
      new: false,
      best: true,
      inCart: false,
      inFavorites: false,
      available: 5,
    },
    {
      id: 11,
      img: require('./images/books/book1.png'),
      title: 'Тихие слова любви',
      author: 'Сара Джио11',
      cost: 2990,
      new: true,
      best: false,
      inCart: false,
      inFavorites: false,
      available: 5,
      genre: 'hud-lit'
    },
    {
      id: 12,
      img: require('./images/books/book1.png'),
      title: 'Тихие слова любви',
      author: 'Сара Джио12',
      cost: 2990,
      new: true,
      best: true,
      inCart: false,
      inFavorites: false,
      available: 5,
    },
  ]